In [64]:
%matplotlib widget
from ipywidgets import *
import numpy as np
import k3d
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar, brentq, minimize
from sloppy.optic import *
from sloppy.raytracing import *
from sloppy.abcd import *
from sloppy.utils import *
from sloppy.tools import *

In [26]:
from cavities.historical import OriginalTwister

In [27]:
waists_vs_param(OriginalTwister, 'betal', 3e-2, N=100)
res = degeneracy_length(OriginalTwister, 'betal', 3e-2)
Ldeg = res.x
print(res)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

     fun: 254943.56700662037
 message: 'Solution found.'
    nfev: 9
  status: 0
 success: True
       x: 31.67531983309997


In [28]:
elements = OriginalTwister(betal=Ldeg)
sys = RaySystem(elements)
system = sys.abcd
print(system.Ltot)
system.waist_at(0)

118.5036122865597


array([0.01922472, 0.01922472])

In [29]:
x = np.linspace(0, system.Ltot, 500)
ws = system.compute_waists(x)

plt.figure()
plt.plot(x, ws)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [30]:
q_1 = system.q_at(system.distlist[1])

In [31]:
q_1 = system.q

In [32]:
q_1

array([[ 0.59893353-0.6176708j ,  0.61194165+0.61194165j,
        -0.34131545-0.5725048j ,  0.24274607-0.48655074j],
       [-0.6246437 +0.5884327j ,  0.61372133+0.61372133j,
         0.24919691+0.47971585j,  0.34795245-0.55426957j]])

In [33]:
ng = 1.460 #1.4537
elements_mm = [Prop(system.distlist[1]),ABCD(CurvedGlass(R=25.0, curv='CC', n2=ng).m), Prop(5.0, n=ng), ABCD(Glass(n1=ng).m),\
               Prop(100.0), ABCD(CurvedGlass(R=69.0, curv='CC', n2=ng).m),Prop(3.8, n=ng),ABCD(Glass(n1=ng).m),\
                Prop(205.0), ABCD(CurvedGlass(R=46.0, curv='CC', n2=ng).m),Prop(2.9, n=ng),ABCD(Glass(n1=ng).m),\
                Prop(550.0), ABCD(CurvedGlass(R=3.1, curv='CC', n2=ng).m),Prop(2.9, n=ng),ABCD(Glass(n1=ng).m),Prop(3.0)] #
abcd_mm = ABCDSystem(elements_mm)

In [76]:
ng = 1.460 #1.4537
elements_claire = [Prop(system.distlist[1]),ABCD(CurvedGlass(R=25.0, curv='CC', n2=ng).m), Prop(5.0, n=ng), ABCD(Glass(n1=ng).m), Prop(100.0)] #
abcd_claire = ABCDSystem(elements_claire)

In [35]:
d_asph = 550.0
d_lens = 175.0-5.0
elements_mm_2 = [Prop(system.distlist[1]),ABCD(CurvedGlass(R=25.0, curv='CC', n2=ng).m), Prop(5.0, n=ng), ABCD(Glass(n1=ng).m),\
               Prop(100.0), ABCD(CurvedGlass(R=69.0, curv='CC', n2=ng).m),Prop(3.8, n=ng),ABCD(Glass(n1=ng).m),\
                Prop(205.0), ABCD(CurvedGlass(R=46.0, curv='CC', n2=ng).m),Prop(2.9, n=ng),ABCD(Glass(n1=ng).m),\
                Prop(d_lens), ABCD(CurvedGlass(R=34.5, curv='CC', n2=ng).m),Prop(2.9, n=ng),ABCD(Glass(n1=ng).m),\
                Prop(d_asph-d_lens), ABCD(CurvedGlass(R=3.1, curv='CC', n2=ng).m),Prop(2.9, n=ng),ABCD(Glass(n1=ng).m),Prop(6.1)] #
abcd_mm_2 = ABCDSystem(elements_mm_2)

In [36]:
x = np.linspace(0, abcd_mm.Ltot, 500)
ws = abcd_mm.compute_waists(x, qin=q_1)
ws2 = abcd_mm_2.compute_waists(x, qin=q_1)
plt.figure()
plt.plot(x, ws)
plt.plot(x, ws2, ls=':')
plt.axhline(0.22*6.2, color='grey')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [44]:
abcd_claire.Ltot

121.32264612750227

In [45]:
q_1

array([[ 0.59893353-0.6176708j ,  0.61194165+0.61194165j,
        -0.34131545-0.5725048j ,  0.24274607-0.48655074j],
       [-0.6246437 +0.5884327j ,  0.61372133+0.61372133j,
         0.24919691+0.47971585j,  0.34795245-0.55426957j]])

In [77]:
x = np.linspace(0, abcd_claire.Ltot, 500)
ws = abcd_claire.compute_waists(x, qin=q_1)
plt.figure()
plt.plot(x, ws)
plt.show()

[[ 0.59893353-0.6176708j   0.61194165+0.61194165j -0.34131545-0.5725048j
   0.24274607-0.48655074j]
 [-0.6246437 +0.5884327j   0.61372133+0.61372133j  0.24919691+0.47971585j
   0.34795245-0.55426957j]]
[[ 0.51594898-0.75686479j  0.67096088+0.49364581j -0.34131545-0.5725048j
   0.24274607-0.48655074j]
 [-0.56405607+0.70506677j  0.69831955+0.47896091j  0.24919691+0.47971585j
   0.34795245-0.55426957j]]
[[ 0.43296442-0.89605877j  0.72998011+0.37534998j -0.34131545-0.5725048j
   0.24274607-0.48655074j]
 [-0.50346844+0.82170083j  0.78291778+0.34420049j  0.24919691+0.47971585j
   0.34795245-0.55426957j]]
[[ 0.34997987-1.03525275j  0.78899934+0.25705414j -0.34131545-0.5725048j
   0.24274607-0.48655074j]
 [-0.4428808 +0.93833489j  0.867516  +0.20944006j  0.24919691+0.47971585j
   0.34795245-0.55426957j]]
[[ 0.26699531-1.17444673j  0.84801857+0.1387583j  -0.34131545-0.5725048j
   0.24274607-0.48655074j]
 [-0.38229317+1.05496895j  0.95211422+0.07467964j  0.24919691+0.47971585j
   0.34795245-0.55

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [60]:
BiK = abcd_claire.q_at(abcd_claire.Ltot)

In [84]:
BiK = np.array([[-30.81043428-50.21487107j,  20.97536398-43.70238519j,
   -0.24982627 -0.38919546j,   0.15858079 -0.35168143j],
 [ 22.66411059+42.01227802j,  30.30399403-49.70964281j,
    0.18584738 +0.32481242j,   0.23215709 -0.39909456j]])

In [85]:
B = BiK[:,:2]
K = -1j*BiK[:,2:]
Q = np.linalg.solve(B,K) # Q = B^-1 K
n = 1
lam = 780e-6
di = np.linalg.eigvals(1j*Q)
ws = np.sqrt(lam/(-n*np.pi)*((1/di.imag) if all(di.imag!=0) else np.array([np.nan, np.nan])))

In [86]:
ws

array([1.18899248, 1.19878034])

In [63]:
qp = propBiK(qin, abcd_at(l))

NameError: name 'propBiK' is not defined

In [ ]:
[[-30.81043428-50.21487107j  20.97536398-43.70238519j
   -0.24982627 -0.38919546j   0.15858079 -0.35168143j]
 [ 22.66411059+42.01227802j  30.30399403-49.70964281j
    0.18584738 +0.32481242j   0.23215709 -0.39909456j]]

In [75]:
import numpy as np
from math import floor
import matplotlib.pyplot as plt
from itertools import product


class ABCD:
    """Base class for ABCD objects.
    In addition to the matrix it can store element properties.

    """
    def __init__(self, m):
        if m is None:
            self.m = np.identity(4, dtype=np.float64)
        else:
            self.m = np.array(m)
        
    def __matmul__(self, other):
        return self.m@other.m


class Prop(ABCD):
    """Propagation through space.
    Args:
        L (float): Propagation distance.
        n (float): Index of refraction of the medium.
    """
    def __init__(self, L, n=1.):
        # Returns the ABCD array for propagation through dielectric constant n
        self.L = L
        self.n = n
        m = np.identity(4, dtype=np.float64)
        m[0,2] = L
        m[1,3] = L
        self.m = m
        
    def aberrations(self, chi, k):
        #shape of chi is (4, N, N)
        x, y, sx, sy = chi
        sx2, sy2 = sx@sx, sy@sy
        sx2psy2 = sx2+sy2
        sx2psy2_2 = sx2psy2@sx2psy2
        nonP4 = -self.L*k/8*(sx2psy2_2)
        nonP6 = -self.L*k/16*(sx2psy2_2@sx2psy2)
        #nonP8 = -5*self.dist*k/128*(sx2psy2@sx2psy2@sx2psy2@sx2psy2)
        
        return sum([nonP4, nonP6]) #nonP6, nonP8 

class Rot(ABCD):
    """Coordinate transformation through rotation.
    Args:
        r (ndarray): 2x2 rotation matrix.
    """
    def __init__(self, r):
        # Returns the ABCD array for basis rotation with 2x2 matrix r
        self.r = r
        m = np.identity(4, dtype=np.float64)
        m[0:2,0:2] = r
        m[2:4,2:4] = r
        self.m = m
        
def ThickLens(d, n1=1., n2=1., R1=None, R2=None):
    """Composite ABCD matrix for thick lens.
    Args:
        R1 (float): Radius of curvature of the first surface (None is flat).
        R2 (float): Radius of curvature of the second surface (None is flat).
        n1 (float): Index of refraction outside the lens.
        n2 (float): Index of refraction inside the lens.
    """
    return [Interface(n1, n2, R1), Prop(d, n2), Interface(n2, n1, R2)]

class ABCDSystem:
    """System comprised of 4x4 ABCD matrices of optical elements and propagation in 2D.
    
    Can obtain different mode properties (waists, eigenvectors) at positions on the optical axis.
    Instead of the complex q parameter for one-dimensional system (2x2 matrices) the eigenvector matrix BiK is used throughout the class.
    
    Attributes:
        elements (list): List of :class:`Optic` elements and :class:`Prop` propagation.
        wl (float): Wavelength of the light.

    """
    @staticmethod
    def abcd_from_x(x, distlist, abcdlist, nlist):
        """ABCD matrix as a function of position x along the optical axis."""
        idx = np.where(x>=np.array(distlist))[0][-1]
        return Prop(x-distlist[idx], nlist[idx]).m@abcdlist[idx]
    
    @staticmethod
    def get_conj_pairs(ev):
        """Get the conjugate eigenvectors with the right normalization."""
        ind = [0, 1, 2, 3]
        indout = []
        evout = []
        while len(ind)>0:
            i = ind.pop(0)
            j = ind[np.argsort(np.abs(ev[i].conj()-ev[ind]))[0]]
            if ev[i].imag<ev[j].imag:
                i, j = j, i
            indout.append(i)
            evout.append(ev[i])
            ind.remove(j)
        return indout, evout
    
    @staticmethod
    def wrapAroundFSR(fsr,f):
        return (f%(fsr/2) - (fsr/2)*(1 if floor(f/(fsr/2))%2==1 else 0))        
    
    @staticmethod
    def stability(Mrt):
        """Stability parameter."""
        # seems like maybe the second dimension gives a factor of 2? Maybe we should just use the norm of the eigenvalues
        return np.trace(Mrt)*0.5/2
    
    @staticmethod
    def stability_bool(Mrt):
        """Is the cavity stable?."""
        eps=0.001
        #return all([np.abs(np.linalg.norm(eva)-1)<eps for eva in np.linalg.eigvals(Mrt)])
        return all([(np.abs(eva)-1)<eps for eva in np.linalg.eigvals(Mrt)])
    
    @staticmethod
    def wrap_fsr(f, fsr):
        return np.mod(f,0.5*fsr) - 0.5*fsr*np.where(np.floor(2.*f/fsr)%2==1, 1, 0)
    
    def __init__(self, elements, wl = 780e-6):
        #unwarp possible nested elements
        self.elements = []
        for ele in elements:
            if isinstance(ele, list):
                self.elements.extend(ele)
            else:
                self.elements.append(ele)
        self.wl = wl
        self.k = 2*np.pi/wl
        #build functions
        distlist=[] #cumulative distances
        #optDistlist=[] #cumulative optical distances
        abcdlist=[] #cumulative abcd matrices
        nlist = []
        dtot=0.0
        dOptTot=0.0
        abcd=np.identity(4, dtype=np.float64)
        for ele in self.elements:
            # check if ele is a propagation or other ABCD matrix
            if isinstance(ele, Prop):
                abcdlist.append(abcd.copy())
                distlist.append(dtot)
                nlist.append(ele.n)
                dtot=dtot+ele.L
                dOptTot=dOptTot+ele.L*ele.n
                abcd=ele.m@abcd
            else:
                abcd=ele.m@abcd

        abcdlist.append(abcd.copy())
        distlist.append(dtot)
        #optDistlist.append(dOptTot)
        nlist.append(nlist[-1]) #TODO: Check this!
        
        self.abcd_rt = abcd
        self.distlist = distlist
        #self.optDistlist = optDistlist
        self.abcdlist = abcdlist
        self.nlist = nlist
        self.Ltot = dtot
        self.LOptot = dOptTot
        self.fsr = 2.99792458e8/(dOptTot*1e-3)
        
        self.abcd_fct = lambda x: self.abcd_from_x(x, distlist, abcdlist, nlist)
        
        #compute mode
        #self.q, self.m = self.solve_mode(self.abcd_rt)
        self.q = self.M2BiK(self.abcd_rt)
        self.m = self.stability(self.abcd_rt)
        #self.is_stable = np.abs(self.stability(self.abcd_rt))<1.
        self.is_stable = self.stability_bool(self.abcd_rt)
        #assert self.m<1 , "Mode not stable!"
        #print("No eigenmode found!")
        
    def M2BiK(self, Mrt):
        """Get eigenvectors from ABCD matrix and normalize."""
        # choose properly normalized pair if we can
        G = np.array([[0,0,1,0], [0,0,0,1], [-1,0,0,0], [0,-1,0,0]])
        ev, mus = np.linalg.eig(Mrt)
        nn0 = [mus[:,i].T.conj()@G@mus[:,i] for i in range(len(mus))]
        if any([ ni == 0 for ni in nn0]):
            nn0 = np.array([1,1,1,1])
        musN = [mus[:,i]*np.sqrt(2/nn0[i]) for i in range(len(mus))]
        nn1 = np.array([musN[i].T.conj()@G@musN[i] for i in range(len(musN))])
        goodIdx = [np.abs((ni-(-2j)))<0.0001 for ni in nn1]
        if np.sum(goodIdx)==2:
            return np.array(musN)[goodIdx]
        else:   # But if unstable or some weird numerics or something,....
            ind, es = ABCDSystem.get_conj_pairs(ev)
            mus = mus[:,ind]
            N = [mus[:,i].T.conj()@G@mus[:,i] for i in range(2)]
            if any([ Ni == 0 for Ni in N]):
                N = np.ones(np.shape(N))
            musN = np.stack([mus[:,i]*np.sqrt(2/N[i]) for i in range(2)], axis=0)
            return musN
        
    def M2waistNew(self, Mrt):
        ev, mus = np.linalg.eig(Mrt)
        G = np.array([[0,0,1,0], [0,0,0,1], [-1,0,0,0], [0,-1,0,0]])
        #Normalize the eigenvectors and take the ones that are normalized to -2j
        N = [mus[:,i].T.conj()@G@mus[:,i] for i in range(4)]
        musN = np.stack([mus[:,i]*np.sqrt(2/N[i]) for i in range(4)], axis=1)
        N = np.array([musN[:,i].T.conj()@G@musN[:,i] for i in range(4)])
        #print(N)
        idx = np.where(np.abs(N.imag+2)<1e-5)[0]
        idx = idx[::-1]
        musN = musN[:,idx]
        #Build B and K matrix, this is very sensitive! Double check again, see https://journals.aps.org/pra/pdf/10.1103/PhysRevA.75.033819
        B = np.array([[ musN[0,0], musN[1,0] ],[ musN[0,1], musN[1,1] ]])
        K = -1j*np.array([[ musN[2,0], musN[3,0] ],[ musN[2,1], musN[3,1] ]])
        # Q = B^-1 K
        Q = np.linalg.solve(B,K) 
        di = np.linalg.eigvals(1j*Q)
        ws = np.sqrt(self.wl/(-n*np.pi)*((1/di.imag) if all(di.imag!=0) else np.array([np.nan, np.nan])))
        return {'ws': ws, 'B': B, 'K': K, 'Q': Q, 'mu': musN}

    def M2freq(self, Mrt, s=3):
        """Get transverse mode frequencies from ABCD matrix and roundtrip lentgh."""
        if not self.is_stable:
            return [np.nan, np.nan], [np.nan, np.nan]
        ev = np.linalg.eigvals(Mrt)
        freqs = np.angle(ev)*self.fsr/(2*np.pi)
        freqsA = np.sort(freqs)[-1:-3:-1]
        #freqsB = freqsA - fsr
        freqsC = ABCDSystem.wrap_fsr(s*freqsA, self.fsr) #same as matts version, only vectorized freqsC = np.array(list(self.wrapAroundFSR(self.fsr, 3.*f) for f in freqsA))
        return freqsA, freqsC
    
    def solve_mode(self, BiK, n=1.):
        """Get waists (diagonal) from eigenvectors."""
        #if not self.is_stable:
        #    return [0, 0]
        B = BiK[:,:2]
        K = -1j*BiK[:,2:]
        lam = self.wl
        Q = np.linalg.solve(B,K) # Q = B^-1 K
        di = np.linalg.eigvals(1j*Q)
        ws = np.sqrt(lam/(-n*np.pi)*((1/di.imag) if all(di.imag!=0) else np.array([np.nan, np.nan])))
        return ws
    
    def propBiK(self, BiK, M):
        """Propagate eigenvector matrix BiK with ABCD matrix M."""
        BiKz = BiK@M.T
        return BiKz
        
    def abcd_at(self, x):
        """Get cumulative ABCD matrix up to position x on the optical axis."""
        idx = np.where(x>=np.array(self.distlist))[0][-1]
        return Prop(x-self.distlist[idx], self.nlist[idx]).m@self.abcdlist[idx]
    
    def n_at(self, x):
        """Get index of refraction at position x to get right waists."""
        idx = np.where(x>=np.array(self.distlist))[0][-1]
        return self.nlist[idx]
    
    def waist_at(self, x):
        """Get waists at position x on the optical axis."""
        qp = self.propBiK(self.q, self.abcd_at(x))
        return self.solve_mode(qp, self.n_at(x))
    
    def compute_waists(self, x, qin=None):
        """Get waists at array of positions x on the optical axis."""
        if qin is None:
            qin = self.q
        ws = np.zeros((x.shape[0], 2))
        for i, l in enumerate(x):
            qp = self.propBiK(qin, self.abcd_at(l))
            print(qp)
            ws[i,:] = self.solve_mode(qp, self.n_at(l))
        return ws
    
    def q_at(self, x):
        return self.propBiK(self.q, self.abcd_at(x))
        
    def get_freqs(self, s=3):
        return self.M2freq(self.abcd_rt, s=s)
    
    def make_realspace(self, a=5., b=None, N=200):
        if b is None:
            b=a
        ws = self.waist_at(0)
        xx=np.linspace(-a*ws[0], a*ws[0], N)
        dx = xx[1]-xx[0]
        yy=np.linspace(-b*ws[1], b*ws[1], N)
        dy = yy[1]-y[0]
        x, y = np.meshgrid(xx,yy, indexing='ij')
        r = np.dstack([x,y])
        self.r = r
    
    @staticmethod
    def chi_wf(phi, k):
        pdx = np.gradient(phi, dx, axis=0)
        pdy = np.gradient(phi, dx, axis=1)
        px = phi*x
        py = phi*y
        return np.stack([px, py, 1j*pdx/k, 1j*pdy/k], axis=0)

    
def propagate_ABCD(mu, M, Nrt=100):
    rs = np.empty((Nrt+1,4))
    r = mu.copy()
    rs[0,:] = r
    for i in range(Nrt):
        r = M@r
        rs[i+1,:] = r
    return rs
